databases:
  - name: memory-db
    region: oregon

services:
  # Main MCP Server
  - type: web
    name: mcp-server
    env: docker
    repo: https://github.com/DuckshotPro/memory-function-ai.git
    dockerContext: ./mcp_server
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: memory-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

  # Conversation Feeder Service
  - type: web
    name: conversation-feeder
    env: docker
    repo: https://github.com/DuckshotPro/memory-function-ai.git
    dockerContext: ./conversation_feeder
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: memory-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: FEEDER_AUTH_TOKEN
        sync: false