"""Add embedding column and enable pgvector

Revision ID: 20250926_pgvector
Revises: 20250926_initial
Create Date: 2025-09-26 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '20250926_pgvector'
down_revision = '20250926_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('messages', sa.Column('embedding', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('messages', 'embedding')
    op.execute("DROP EXTENSION vector")
    # ### end Alembic commands ###
